import { useMemo, useState } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { useAuth } from "@/lib/auth";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useToast } from "@/hooks/use-toast";
import { CalendarDays, CalendarX2, Clock, Lock, Plus, Sparkles, Trash2 } from "lucide-react";
import { Navbar } from "@/components/Navbar";
import { PerplexityAttribution } from "@/components/PerplexityAttribution";
import { ScheduleCard } from "@/components/escalas/ScheduleCard";
import { ScheduleFormDialog } from "@/components/escalas/ScheduleFormDialog";
import { AutoGenerateDialog } from "@/components/escalas/AutoGenerateDialog";
import { TeamRolesManager } from "@/components/escalas/TeamRolesManager";
import {
  SCHEDULE_ROLE_LABELS,
  type SafeUser, type Schedule, type Unavailability,
} from "@shared/schema";
import { formatScheduleDate, ROLE_BADGE_CLASSES, ROLE_ICONS, todayISO } from "@/lib/escalas";

export default function Escalas() {
  const { user, isAuthenticated } = useAuth();
  const [view, setView] = useState<"voluntario" | "admin">("voluntario");
  const isAdmin = !!user?.isAdmin;

  const schedulesQuery = useQuery<Schedule[]>({
    queryKey: ["/api/schedules"],
    refetchInterval: 10000,
    enabled: isAuthenticated,
  });
  const unavailabilityQuery = useQuery<Unavailability[]>({
    queryKey: ["/api/unavailability"],
    enabled: isAuthenticated,
  });
  const usersQuery = useQuery<SafeUser[]>({
    queryKey: ["/api/users"],
    enabled: isAuthenticated && isAdmin,
  });

  const schedules = schedulesQuery.data ?? [];
  const unavailability = unavailabilityQuery.data ?? [];
  const users = usersQuery.data ?? [];

  return (
    <div className="min-h-screen bg-background">
      <Navbar subtitle="Escalas de Voluntários" />

      <main className="max-w-6xl mx-auto px-4 py-6">
        {!isAuthenticated ? (
          <LoginRequired />
        ) : (
          <>
            <div className="flex items-center justify-between gap-4 flex-wrap mb-6">
              <h2 className="text-lg font-bold uppercase tracking-wider flex items-center gap-2">
                <CalendarDays className="w-5 h-5 text-primary" /> Escalas
              </h2>
              {isAdmin && (
                <Tabs value={view} onValueChange={(v) => setView(v as "voluntario" | "admin")}>
                  <TabsList data-testid="tabs-escalas-view">
                    <TabsTrigger value="voluntario" data-testid="tab-voluntario">Voluntário</TabsTrigger>
                    <TabsTrigger value="admin" data-testid="tab-admin">Administração</TabsTrigger>
                  </TabsList>
                </Tabs>
              )}
            </div>

            {schedulesQuery.isLoading ? (
              <Card className="p-8 text-center text-muted-foreground">Carregando...</Card>
            ) : view === "admin" && isAdmin ? (
              <AdminView users={users} schedules={schedules} unavailability={unavailability} />
            ) : (
              <VolunteerView
                currentUserId={user!.id}
                schedules={schedules}
                unavailability={unavailability}
              />
            )}
          </>
        )}

        <footer className="mt-12 pb-8 text-center">
          <PerplexityAttribution />
        </footer>
      </main>
    </div>
  );
}

function LoginRequired() {
  return (
    <Card className="max-w-md mx-auto p-8 text-center space-y-4">
      <div className="mx-auto w-14 h-14 rounded-full bg-primary/10 flex items-center justify-center">
        <Lock className="w-6 h-6 text-primary" />
      </div>
      <div className="space-y-1">
        <h3 className="font-bold">Área restrita</h3>
        <p className="text-sm text-muted-foreground">
          As escalas são visíveis apenas para membros logados da equipe de comunicação.
        </p>
      </div>
      <Link href="/login?next=/escalas">
        <Button className="w-full" data-testid="button-escalas-login">Fazer login</Button>
      </Link>
    </Card>
  );
}

// ── Volunteer view (logged-in user) ─────────────────────────────────────────

function VolunteerView({ currentUserId, schedules, unavailability }: {
  currentUserId: number;
  schedules: Schedule[];
  unavailability: Unavailability[];
}) {
  const today = todayISO();

  const upcoming = useMemo(
    () => schedules.filter((s) => s.eventDate >= today),
    [schedules, today]
  );

  const myAssignments = useMemo(() => {
    return upcoming
      .map((schedule) => ({
        schedule,
        roles: schedule.assignments.filter((a) => a.volunteerId === currentUserId).map((a) => a.role),
      }))
      .filter((item) => item.roles.length > 0);
  }, [upcoming, currentUserId]);

  return (
    <div className="space-y-8">
      {/* My upcoming assignments */}
      <section className="space-y-3">
        <h3 className="text-sm font-bold uppercase tracking-wider">Minhas próximas escalas</h3>
        {myAssignments.length === 0 ? (
          <Card className="p-6 text-center text-muted-foreground text-sm">
            Você não está escalado em nenhum evento próximo.
          </Card>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {myAssignments.map(({ schedule, roles }) => (
              <Card key={schedule.id} className="p-5 space-y-3 border-primary/20" data-testid={`card-my-assignment-${schedule.id}`}>
                <div>
                  <p className="text-sm font-bold">{formatScheduleDate(schedule.eventDate)}</p>
                  <div className="flex items-center gap-2 mt-1 text-xs text-muted-foreground">
                    <Clock className="w-3 h-3" />
                    <span>{schedule.eventTime}</span>
                    <span>·</span>
                    <span className="font-medium text-foreground">{schedule.title}</span>
                  </div>
                </div>
                <div className="flex flex-wrap gap-1.5">
                  {roles.map((role) => {
                    const Icon = ROLE_ICONS[role];
                    return (
                      <Badge key={role} className={`${ROLE_BADGE_CLASSES[role]} border`}>
                        <Icon className="w-3 h-3 mr-1" /> {SCHEDULE_ROLE_LABELS[role]}
                      </Badge>
                    );
                  })}
                </div>
                {schedule.notes && <p className="text-xs text-muted-foreground">{schedule.notes}</p>}
              </Card>
            ))}
          </div>
        )}
      </section>

      {/* My availability */}
      <MyAvailability currentUserId={currentUserId} unavailability={unavailability} />

      {/* Full upcoming schedule */}
      <section className="space-y-3">
        <h3 className="text-sm font-bold uppercase tracking-wider">Próximas escalas da equipe</h3>
        {upcoming.length === 0 ? (
          <Card className="p-6 text-center text-muted-foreground text-sm">
            Nenhuma escala publicada ainda. Volte em breve!
          </Card>
        ) : (
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-3">
            {upcoming.map((schedule) => (
              <ScheduleCard key={schedule.id} schedule={schedule} highlightVolunteerId={currentUserId} />
            ))}
          </div>
        )}
      </section>
    </div>
  );
}

// Volunteers record days they cannot serve; auto-generation skips those days
function MyAvailability({ currentUserId, unavailability }: {
  currentUserId: number;
  unavailability: Unavailability[];
}) {
  const { toast } = useToast();
  const [newDate, setNewDate] = useState("");
  const today = todayISO();

  // Admins receive everyone's entries — filter down to the current user's
  const myEntries = useMemo(
    () => unavailability.filter((u) => u.userId === currentUserId && u.date >= today),
    [unavailability, currentUserId, today]
  );

  const addMutation = useMutation({
    mutationFn: async (date: string) => {
      const res = await apiRequest("POST", "/api/unavailability", { date });
      return res.json();
    },
    onSuccess: () => {
      setNewDate("");
      queryClient.invalidateQueries({ queryKey: ["/api/unavailability"] });
      toast({ title: "Indisponibilidade registrada" });
    },
    onError: () => {
      toast({ title: "Erro", description: "Não foi possível registrar a data.", variant: "destructive" });
    },
  });

  const removeMutation = useMutation({
    mutationFn: async (id: number) => {
      await apiRequest("DELETE", `/api/unavailability/${id}`);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/unavailability"] });
    },
  });

  return (
    <section className="space-y-3">
      <h3 className="text-sm font-bold uppercase tracking-wider flex items-center gap-2">
        <CalendarX2 className="w-4 h-4 text-primary" /> Minha disponibilidade
      </h3>
      <Card className="p-5 space-y-4">
        <p className="text-sm text-muted-foreground">
          Registre os dias em que você <span className="font-semibold text-foreground">não pode</span> servir.
          A geração automática de escalas não vai te escalar nessas datas.
        </p>

        <div className="flex gap-2 max-w-sm">
          <Input
            type="date"
            min={today}
            value={newDate}
            onChange={(e) => setNewDate(e.target.value)}
            data-testid="input-unavailable-date"
          />
          <Button
            onClick={() => newDate && addMutation.mutate(newDate)}
            disabled={!newDate || addMutation.isPending}
            data-testid="button-add-unavailable"
          >
            <Plus className="w-4 h-4 mr-1" /> Adicionar
          </Button>
        </div>

        {myEntries.length > 0 && (
          <div className="flex flex-wrap gap-2">
            {myEntries.map((entry) => (
              <Badge key={entry.id} variant="secondary" className="gap-1 pr-1" data-testid={`badge-unavailable-${entry.id}`}>
                {formatScheduleDate(entry.date)}
                <button
                  className="ml-1 rounded-full hover:text-destructive"
                  onClick={() => removeMutation.mutate(entry.id)}
                  title="Remover"
                  data-testid={`button-remove-unavailable-${entry.id}`}
                >
                  <Trash2 className="w-3 h-3" />
                </button>
              </Badge>
            ))}
          </div>
        )}
      </Card>
    </section>
  );
}

// ── Admin view ──────────────────────────────────────────────────────────────

function AdminView({ users, schedules, unavailability }: {
  users: SafeUser[];
  schedules: Schedule[];
  unavailability: Unavailability[];
}) {
  const { toast } = useToast();
  const [formOpen, setFormOpen] = useState(false);
  const [autoOpen, setAutoOpen] = useState(false);
  const [editingSchedule, setEditingSchedule] = useState<Schedule | null>(null);
  const [showPast, setShowPast] = useState(false);

  const today = todayISO();
  const visibleSchedules = useMemo(
    () => (showPast ? schedules : schedules.filter((s) => s.eventDate >= today)),
    [schedules, showPast, today]
  );

  const deleteMutation = useMutation({
    mutationFn: async (id: number) => {
      await apiRequest("DELETE", `/api/schedules/${id}`);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/schedules"] });
      toast({ title: "Escala removida" });
    },
    onError: () => {
      toast({ title: "Erro", description: "Não foi possível remover a escala.", variant: "destructive" });
    },
  });

  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
      {/* Team roles */}
      <div className="lg:col-span-1">
        <TeamRolesManager users={users} unavailability={unavailability} />
      </div>

      {/* Schedules */}
      <div className="lg:col-span-2 space-y-4">
        <div className="flex items-center justify-between gap-3 flex-wrap">
          <div className="flex items-center gap-2">
            <Button onClick={() => { setEditingSchedule(null); setFormOpen(true); }} data-testid="button-new-schedule">
              <Plus className="w-4 h-4 mr-1" /> Nova escala
            </Button>
            <Button variant="secondary" onClick={() => setAutoOpen(true)} data-testid="button-auto-generate">
              <Sparkles className="w-4 h-4 mr-1" /> Gerar automaticamente
            </Button>
          </div>
          <div className="flex items-center gap-2">
            <Checkbox
              id="show-past"
              checked={showPast}
              onCheckedChange={(checked) => setShowPast(checked === true)}
              data-testid="checkbox-show-past"
            />
            <Label htmlFor="show-past" className="font-normal cursor-pointer text-sm text-muted-foreground">
              Mostrar anteriores
            </Label>
          </div>
        </div>

        {visibleSchedules.length === 0 ? (
          <Card className="p-8 text-center text-muted-foreground text-sm">
            Nenhuma escala {showPast ? "cadastrada" : "futura"}. Crie manualmente ou use a geração automática.
          </Card>
        ) : (
          <div className="space-y-3">
            {visibleSchedules.map((schedule) => (
              <ScheduleCard
                key={schedule.id}
                schedule={schedule}
                onEdit={(s) => { setEditingSchedule(s); setFormOpen(true); }}
                onDelete={(s) => deleteMutation.mutate(s.id)}
              />
            ))}
          </div>
        )}
      </div>

      <ScheduleFormDialog
        open={formOpen}
        onOpenChange={setFormOpen}
        volunteers={users}
        unavailability={unavailability}
        schedule={editingSchedule}
      />
      <AutoGenerateDialog
        open={autoOpen}
        onOpenChange={setAutoOpen}
        volunteers={users}
        schedules={schedules}
        unavailability={unavailability}
      />
    </div>
  );
}
