import { useMemo, useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { format, parseISO } from "date-fns";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle,
} from "@/components/ui/dialog";
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue,
} from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";
import { AlertTriangle, ChevronDown, ChevronUp, Plus, RotateCcw, Sparkles, Trash2 } from "lucide-react";
import {
  SCHEDULE_ROLES, SCHEDULE_ROLE_LABELS,
  type SafeUser, type Schedule, type ScheduleRole, type Unavailability,
} from "@shared/schema";
import {
  autoGenerateSchedules, datesForWeekdays, datesInPeriod, defaultPlanForWeekday,
  formatScheduleDate, makeScheduleSlot, todayISO, DEFAULT_SCHEDULE_TITLE,
  type AutoGenerateResult, type PlanByWeekday, type ScheduleSlot, type WeekdayPlan,
} from "@/lib/escalas";

// Os dias em que a igreja tem culto regularmente
const MAIN_WEEKDAY_OPTIONS = [
  { value: 0, label: "Domingo" },
  { value: 4, label: "Quinta" },
  { value: 6, label: "Sábado" },
];

// Ficam escondidos atrás de "Outros dias": raramente usados, mas existem para
// eventos ocasionais fora dos dias de culto.
const OTHER_WEEKDAY_OPTIONS = [
  { value: 1, label: "Segunda" },
  { value: 2, label: "Terça" },
  { value: 3, label: "Quarta" },
  { value: 5, label: "Sexta" },
];

interface AutoGenerateDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  volunteers: SafeUser[]; // registered users; only those with roles are scheduled
  schedules: Schedule[];
  unavailability: Unavailability[];
}

export function AutoGenerateDialog({ open, onOpenChange, volunteers, schedules, unavailability }: AutoGenerateDialogProps) {
  const { toast } = useToast();
  const [startDate, setStartDate] = useState(todayISO());
  const [weeks, setWeeks] = useState("4");
  // Cada dia selecionado guarda seus cultos (horário + funções a preencher), as
  // datas do período sem culto e as datas com horário próprio.
  // Domingo já começa com dois cultos: manhã e noite.
  const [plans, setPlans] = useState<PlanByWeekday>({ 0: defaultPlanForWeekday(0) });
  const [showOtherDays, setShowOtherDays] = useState(false);

  const otherDaysSelected = OTHER_WEEKDAY_OPTIONS.filter(({ value }) => plans[value]).length;

  // As datas concretas de cada dia marcado. A mesma função alimenta a geração,
  // então as chaves de exclusão e de horário próprio casam com o que está na tela.
  const datesByWeekday = useMemo(() => {
    const byWeekday: Record<number, string[]> = {};
    if (!startDate) return byWeekday;
    const start = parseISO(startDate);
    if (Number.isNaN(start.getTime())) return byWeekday;
    for (const weekday of Object.keys(plans)) {
      byWeekday[Number(weekday)] = datesInPeriod(start, Number(weeks), Number(weekday));
    }
    return byWeekday;
  }, [startDate, weeks, plans]);

  const result = useMemo(() => {
    const empty: AutoGenerateResult = { generated: [], skipped: [] };
    if (!startDate) return empty;
    const dates = datesForWeekdays(parseISO(startDate), Number(weeks), plans);
    if (dates.length === 0) return empty;
    return autoGenerateSchedules({
      volunteers,
      existing: schedules,
      unavailability,
      dates,
    });
  }, [startDate, weeks, plans, volunteers, schedules, unavailability]);

  const mutation = useMutation({
    mutationFn: async () => {
      const res = await apiRequest("POST", "/api/schedules/bulk", { schedules: result.generated });
      return res.json();
    },
    onSuccess: (created: Schedule[]) => {
      queryClient.invalidateQueries({ queryKey: ["/api/schedules"] });
      toast({ title: "Escalas geradas", description: `${created.length} escala(s) criada(s) automaticamente.` });
      onOpenChange(false);
    },
    onError: (err: Error) => {
      toast({
        title: "Erro",
        description: err.message || "Não foi possível gerar as escalas.",
        variant: "destructive",
      });
    },
  });

  // Marcar um dia já traz os horários padrão dele, com todas as funções.
  // Desmarcar apaga também as exceções de data daquele dia.
  const toggleWeekday = (weekday: number) => {
    setPlans((prev) => {
      const next = { ...prev };
      if (next[weekday]) {
        delete next[weekday];
      } else {
        next[weekday] = defaultPlanForWeekday(weekday);
      }
      return next;
    });
  };

  const updatePlan = (weekday: number, update: (plan: WeekdayPlan) => WeekdayPlan) => {
    setPlans((prev) => {
      const plan = prev[weekday];
      if (!plan) return prev;
      return { ...prev, [weekday]: update(plan) };
    });
  };

  // ── Título e horários padrão do dia da semana ────────────────────────────

  const setPlanTitle = (weekday: number, title: string) =>
    updatePlan(weekday, (plan) => ({ ...plan, title }));

  const updateSlots = (weekday: number, update: (slots: ScheduleSlot[]) => ScheduleSlot[]) =>
    updatePlan(weekday, (plan) => ({ ...plan, slots: update(plan.slots) }));

  const addSlot = (weekday: number) =>
    updateSlots(weekday, (slots) => [...slots, makeScheduleSlot()]);

  const removeSlot = (weekday: number, slotId: string) =>
    updateSlots(weekday, (slots) => slots.filter((s) => s.id !== slotId));

  const setSlotTime = (weekday: number, slotId: string, time: string) =>
    updateSlots(weekday, (slots) => slots.map((s) => (s.id === slotId ? { ...s, time } : s)));

  const toggleSlotRole = (weekday: number, slotId: string, role: ScheduleRole) =>
    updateSlots(weekday, (slots) =>
      slots.map((s) =>
        s.id === slotId
          ? {
              ...s,
              roles: s.roles.includes(role) ? s.roles.filter((r) => r !== role) : [...s.roles, role],
            }
          : s
      )
    );

  // ── Exceções por data ─────────────────────────────────────────────────────

  const toggleDate = (weekday: number, date: string) =>
    updatePlan(weekday, (plan) => ({
      ...plan,
      excludedDates: plan.excludedDates.includes(date)
        ? plan.excludedDates.filter((d) => d !== date)
        : [...plan.excludedDates, date],
    }));

  // Nome próprio da data. Campo vazio não guarda nada: apagar já é o "restaurar",
  // e o placeholder mostra qual nome será herdado — não precisa de botão.
  const setDateTitle = (weekday: number, date: string, title: string) =>
    updatePlan(weekday, (plan) => {
      const titleByDate = { ...plan.titleByDate };
      if (title) {
        titleByDate[date] = title;
      } else {
        delete titleByDate[date];
      }
      return { ...plan, titleByDate };
    });

  // A primeira edição de uma data copia os horários do dia da semana: dali em
  // diante ela segue por conta própria, e mexer no padrão do dia não a afeta.
  const updateDateSlots = (
    weekday: number,
    date: string,
    update: (slots: ScheduleSlot[]) => ScheduleSlot[],
  ) =>
    updatePlan(weekday, (plan) => ({
      ...plan,
      slotsByDate: {
        ...plan.slotsByDate,
        [date]: update(
          plan.slotsByDate[date] ?? plan.slots.map((slot) => ({ ...slot, roles: [...slot.roles] })),
        ),
      },
    }));

  const setDateSlotTime = (weekday: number, date: string, slotId: string, time: string) =>
    updateDateSlots(weekday, date, (slots) =>
      slots.map((s) => (s.id === slotId ? { ...s, time } : s))
    );

  const addDateSlot = (weekday: number, date: string) =>
    updateDateSlots(weekday, date, (slots) => [...slots, makeScheduleSlot()]);

  const removeDateSlot = (weekday: number, date: string, slotId: string) =>
    updateDateSlots(weekday, date, (slots) => slots.filter((s) => s.id !== slotId));

  const resetDate = (weekday: number, date: string) =>
    updatePlan(weekday, (plan) => {
      const slotsByDate = { ...plan.slotsByDate };
      delete slotsByDate[date];
      return { ...plan, slotsByDate };
    });

  const weekdayCard = ({ value, label }: { value: number; label: string }) => (
    <WeekdayCard
      key={value}
      weekday={value}
      label={label}
      plan={plans[value]}
      dates={datesByWeekday[value] ?? []}
      onToggle={() => toggleWeekday(value)}
      onTitleChange={(next) => setPlanTitle(value, next)}
      onAddSlot={() => addSlot(value)}
      onRemoveSlot={(slotId) => removeSlot(value, slotId)}
      onTimeChange={(slotId, time) => setSlotTime(value, slotId, time)}
      onToggleRole={(slotId, role) => toggleSlotRole(value, slotId, role)}
      onToggleDate={(date) => toggleDate(value, date)}
      onDateTitleChange={(date, next) => setDateTitle(value, date, next)}
      onDateTimeChange={(date, slotId, time) => setDateSlotTime(value, date, slotId, time)}
      onDateAddSlot={(date) => addDateSlot(value, date)}
      onDateRemoveSlot={(date, slotId) => removeDateSlot(value, date, slotId)}
      onDateReset={(date) => resetDate(value, date)}
    />
  );

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Sparkles className="w-4 h-4 text-primary" /> Gerar escalas automaticamente
          </DialogTitle>
          <DialogDescription>
            Os voluntários são distribuídos por rodízio, priorizando quem tem menos escalas e respeitando as indisponibilidades registradas — inclusive o período (manhã, tarde ou noite) de cada culto. “Em treinamento” só entra nos horários em que for marcada, e quem cai nela fica de fora das outras funções daquele período.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="gen-start">A partir de</Label>
              <Input
                id="gen-start"
                type="date"
                value={startDate}
                onChange={(e) => setStartDate(e.target.value)}
                data-testid="input-gen-start"
              />
            </div>
            <div className="space-y-2">
              <Label>Período</Label>
              <Select value={weeks} onValueChange={setWeeks}>
                <SelectTrigger data-testid="select-gen-weeks">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {[1, 2, 4, 6, 8].map((w) => (
                    <SelectItem key={w} value={String(w)}>{w} semana{w > 1 ? "s" : ""}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>

          <div className="space-y-2">
            <div>
              <Label>Dias de culto</Label>
              <p className="text-xs text-muted-foreground mt-1">
                Cada dia tem o seu título, os seus horários e as suas funções — cada horário
                vira uma escala. Domingo já vem com os dois cultos (manhã e noite). Abra “Datas
                no período” para desmarcar os dias sem culto e dar nome ou horário próprio a
                datas específicas.
              </p>
            </div>
            <div className="space-y-2">
              {MAIN_WEEKDAY_OPTIONS.map(weekdayCard)}
            </div>

            {/* Dias fora dos cultos regulares: escondidos, mas disponíveis para
                eventos ocasionais */}
            <div className="space-y-2">
              <Button
                type="button"
                variant="ghost"
                size="sm"
                className="w-full justify-center text-muted-foreground"
                onClick={() => setShowOtherDays((v) => !v)}
                data-testid="button-other-weekdays"
              >
                {showOtherDays ? <ChevronUp className="w-4 h-4 mr-1" /> : <ChevronDown className="w-4 h-4 mr-1" />}
                Outros dias
                {!showOtherDays && otherDaysSelected > 0 && (
                  <Badge variant="secondary" className="ml-2 text-xs font-normal">
                    {otherDaysSelected} selecionado{otherDaysSelected > 1 ? "s" : ""}
                  </Badge>
                )}
              </Button>
              {showOtherDays && (
                <div className="space-y-2">
                  {OTHER_WEEKDAY_OPTIONS.map(weekdayCard)}
                </div>
              )}
            </div>
          </div>

          {result.skipped.length > 0 && (
            <div className="flex items-start gap-2 bg-muted/50 border border-border rounded-lg p-3">
              <AlertTriangle className="w-4 h-4 text-muted-foreground mt-0.5 shrink-0" />
              <p className="text-xs text-muted-foreground">
                Ignorados por já possuírem escala:{" "}
                {result.skipped.map(({ date, time }) => `${date} ${time}`).join(", ")}
              </p>
            </div>
          )}

          {/* Preview */}
          <div className="space-y-2">
            <Label>Pré-visualização ({result.generated.length} escala{result.generated.length !== 1 ? "s" : ""})</Label>
            {result.generated.length === 0 ? (
              <p className="text-sm text-muted-foreground border border-border rounded-lg p-4 text-center">
                Nenhuma data disponível com os critérios selecionados.
              </p>
            ) : (
              <div className="space-y-2 max-h-[240px] overflow-y-auto pr-1">
                {result.generated.map((s) => (
                  <div key={`${s.eventDate} ${s.eventTime}`} className="border border-border rounded-lg p-3 space-y-1.5">
                    <div>
                      <p className="text-sm font-semibold">{s.title}</p>
                      <p className="text-xs text-muted-foreground">
                        {formatScheduleDate(s.eventDate)} · {s.eventTime}
                      </p>
                    </div>
                    <div className="flex flex-wrap gap-1.5">
                      {s.assignments.map((a) => (
                        <Badge key={a.role} variant="secondary" className="text-xs font-normal">
                          <span className="font-semibold mr-1">{SCHEDULE_ROLE_LABELS[a.role]}:</span> {a.volunteerName}
                        </Badge>
                      ))}
                      {s.assignments.length === 0 && (
                        <span className="text-xs text-muted-foreground">Sem voluntários elegíveis</span>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>

        <DialogFooter>
          <Button variant="secondary" onClick={() => onOpenChange(false)}>Cancelar</Button>
          <Button
            onClick={() => mutation.mutate()}
            disabled={mutation.isPending || result.generated.length === 0}
            data-testid="button-generate-schedules"
          >
            {mutation.isPending ? "Gerando..." : `Salvar ${result.generated.length} escala(s)`}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// O dia tem alguma data de fora, com horário próprio ou com nome próprio dentro da
// janela atual? Só conta o que está na janela: exceção fora dela não gera nada e
// não é apagada.
function hasDateExceptions(plan: WeekdayPlan | undefined, dates: string[]): boolean {
  if (!plan) return false;
  return dates.some(
    (date) =>
      plan.excludedDates.includes(date) ||
      Boolean(plan.slotsByDate[date]) ||
      Boolean(plan.titleByDate[date]),
  );
}

// Um dia da semana: quando marcado, lista o título, os horários padrão (com suas
// funções) e as datas do período em que eles se aplicam
function WeekdayCard({
  weekday, label, plan, dates,
  onToggle, onTitleChange, onAddSlot, onRemoveSlot, onTimeChange, onToggleRole,
  onToggleDate, onDateTitleChange, onDateTimeChange, onDateAddSlot, onDateRemoveSlot, onDateReset,
}: {
  weekday: number;
  label: string;
  plan?: WeekdayPlan;
  dates: string[];
  onToggle: () => void;
  onTitleChange: (title: string) => void;
  onAddSlot: () => void;
  onRemoveSlot: (slotId: string) => void;
  onTimeChange: (slotId: string, time: string) => void;
  onToggleRole: (slotId: string, role: ScheduleRole) => void;
  onToggleDate: (date: string) => void;
  onDateTitleChange: (date: string, title: string) => void;
  onDateTimeChange: (date: string, slotId: string, time: string) => void;
  onDateAddSlot: (date: string) => void;
  onDateRemoveSlot: (date: string, slotId: string) => void;
  onDateReset: (date: string) => void;
}) {
  // Oito domingos com dois horários cada é lista demais para quem só quer gerar o
  // mês inteiro: o bloco fica fechado, e só abre sozinho se o dia já tiver exceção.
  const [showDates, setShowDates] = useState(() => hasDateExceptions(plan, dates));

  if (!plan) {
    return (
      <div className="border border-border rounded-lg p-3">
        <WeekdayToggle weekday={weekday} label={label} checked={false} onToggle={onToggle} />
      </div>
    );
  }

  const { slots, excludedDates, slotsByDate, titleByDate } = plan;
  const weekdayTitle = plan.title.trim() || DEFAULT_SCHEDULE_TITLE;
  const excludedCount = dates.filter((date) => excludedDates.includes(date)).length;
  const customTimeCount = dates.filter((date) => slotsByDate[date]).length;
  const customTitleCount = dates.filter((date) => titleByDate[date]).length;

  return (
    <div className="border border-border rounded-lg p-3 space-y-2">
      <div className="flex items-center gap-2">
        <WeekdayToggle weekday={weekday} label={label} checked onToggle={onToggle} />
        {slots.length > 1 && (
          <span className="text-xs text-muted-foreground ml-auto">{slots.length} horários</span>
        )}
      </div>

      <div className="space-y-3 pl-6">
        <div className="space-y-1.5">
          <Label htmlFor={`weekday-${weekday}-title`} className="text-xs font-medium text-muted-foreground">
            Título padrão de {label.toLowerCase()}
          </Label>
          <Input
            id={`weekday-${weekday}-title`}
            className="h-8"
            value={plan.title}
            placeholder={DEFAULT_SCHEDULE_TITLE}
            onChange={(e) => onTitleChange(e.target.value)}
            data-testid={`input-weekday-${weekday}-title`}
          />
        </div>

        <div className="space-y-2">
          <p className="text-xs font-medium text-muted-foreground">Horários do dia</p>
          {slots.map((slot, index) => (
            <div key={slot.id} className="border border-border/70 bg-muted/30 rounded-md p-2.5 space-y-2">
              <div className="flex items-center gap-2">
                <Label htmlFor={`weekday-${weekday}-slot-${index}-time`} className="text-xs text-muted-foreground">
                  {slots.length > 1 ? `Horário ${index + 1}` : "Horário"}
                </Label>
                <Input
                  id={`weekday-${weekday}-slot-${index}-time`}
                  type="time"
                  className="w-32 h-8"
                  value={slot.time}
                  onChange={(e) => onTimeChange(slot.id, e.target.value)}
                  data-testid={`input-weekday-${weekday}-slot-${index}-time`}
                />
                {slots.length > 1 && (
                  <Button
                    type="button"
                    variant="ghost"
                    size="icon"
                    className="h-8 w-8 ml-auto"
                    onClick={() => onRemoveSlot(slot.id)}
                    title="Remover horário"
                    data-testid={`button-weekday-${weekday}-remove-slot-${index}`}
                  >
                    <Trash2 className="w-4 h-4 text-muted-foreground" />
                  </Button>
                )}
              </div>

              <div className="flex flex-wrap gap-x-4 gap-y-2">
                {SCHEDULE_ROLES.map((role) => (
                  <div key={role} className="flex items-center gap-2">
                    <Checkbox
                      id={`weekday-${weekday}-slot-${index}-role-${role}`}
                      checked={slot.roles.includes(role)}
                      onCheckedChange={() => onToggleRole(slot.id, role)}
                      data-testid={`checkbox-weekday-${weekday}-slot-${index}-role-${role}`}
                    />
                    <Label
                      htmlFor={`weekday-${weekday}-slot-${index}-role-${role}`}
                      className="font-normal text-sm cursor-pointer"
                    >
                      {SCHEDULE_ROLE_LABELS[role]}
                    </Label>
                  </div>
                ))}
                {slot.roles.length === 0 && (
                  <span className="text-xs text-muted-foreground">
                    Selecione ao menos uma função para gerar escala neste horário.
                  </span>
                )}
              </div>
            </div>
          ))}

          <Button
            type="button"
            variant="ghost"
            size="sm"
            className="text-muted-foreground"
            onClick={onAddSlot}
            data-testid={`button-weekday-${weekday}-add-slot`}
          >
            <Plus className="w-4 h-4 mr-1" /> Adicionar horário
          </Button>
        </div>

        {/* Nem toda data do período tem culto, e as que têm podem ter horário
            próprio. As funções são sempre as do horário padrão do dia. Fechado por
            padrão, mas o resumo das exceções fica visível mesmo fechado — o que
            está de fora nunca pode ficar escondido. */}
        <div className="space-y-2">
          {dates.length === 0 ? (
            <div className="space-y-1">
              <p className="text-xs font-medium text-muted-foreground">Datas no período</p>
              <p className="text-xs text-muted-foreground">
                Informe a data inicial para ver as datas deste dia.
              </p>
            </div>
          ) : (
            <>
              <Button
                type="button"
                variant="ghost"
                size="sm"
                className="w-full justify-start px-2 -ml-2 text-muted-foreground font-medium"
                onClick={() => setShowDates((v) => !v)}
                data-testid={`button-weekday-${weekday}-dates`}
              >
                {showDates ? <ChevronUp className="w-4 h-4 mr-1" /> : <ChevronDown className="w-4 h-4 mr-1" />}
                Datas no período
                <span className="ml-2 flex flex-wrap items-center gap-1.5" data-testid={`text-weekday-${weekday}-date-count`}>
                  {excludedCount > 0 ? (
                    <Badge variant="secondary" className="text-xs font-normal">
                      {dates.length - excludedCount} de {dates.length}
                    </Badge>
                  ) : (
                    <span className="text-xs font-normal">{dates.length} datas</span>
                  )}
                  {customTitleCount > 0 && (
                    <Badge variant="secondary" className="text-xs font-normal">
                      {customTitleCount} com nome próprio
                    </Badge>
                  )}
                  {customTimeCount > 0 && (
                    <Badge variant="secondary" className="text-xs font-normal">
                      {customTimeCount} com horário próprio
                    </Badge>
                  )}
                </span>
              </Button>
              {showDates && (
                <div className="space-y-1.5">
                  {dates.map((date) => (
                    <WeekdayDateRow
                      key={date}
                      weekday={weekday}
                      date={date}
                      slots={slotsByDate[date]}
                      defaultSlots={slots}
                      title={titleByDate[date]}
                      defaultTitle={weekdayTitle}
                      excluded={excludedDates.includes(date)}
                      onToggle={() => onToggleDate(date)}
                      onTitleChange={(next) => onDateTitleChange(date, next)}
                      onTimeChange={(slotId, time) => onDateTimeChange(date, slotId, time)}
                      onAddSlot={() => onDateAddSlot(date)}
                      onRemoveSlot={(slotId) => onDateRemoveSlot(date, slotId)}
                      onReset={() => onDateReset(date)}
                    />
                  ))}
                </div>
              )}
            </>
          )}
        </div>
      </div>
    </div>
  );
}

function WeekdayToggle({ weekday, label, checked, onToggle }: {
  weekday: number;
  label: string;
  checked: boolean;
  onToggle: () => void;
}) {
  return (
    <div className="flex items-center gap-2">
      <Checkbox
        id={`weekday-${weekday}`}
        checked={checked}
        onCheckedChange={onToggle}
        data-testid={`checkbox-weekday-${weekday}`}
      />
      <Label htmlFor={`weekday-${weekday}`} className="font-medium cursor-pointer">{label}</Label>
    </div>
  );
}

// Uma data do período: pode ser desmarcada (não terá culto), pode ter nome próprio
// e pode ter os seus próprios horários, herdados do padrão do dia na primeira edição
function WeekdayDateRow({
  weekday, date, slots, defaultSlots, title, defaultTitle, excluded,
  onToggle, onTitleChange, onTimeChange, onAddSlot, onRemoveSlot, onReset,
}: {
  weekday: number;
  date: string;
  slots?: ScheduleSlot[];
  defaultSlots: ScheduleSlot[];
  title?: string;
  defaultTitle: string;
  excluded: boolean;
  onToggle: () => void;
  onTitleChange: (title: string) => void;
  onTimeChange: (slotId: string, time: string) => void;
  onAddSlot: () => void;
  onRemoveSlot: (slotId: string) => void;
  onReset: () => void;
}) {
  const custom = Boolean(slots);
  const shown = slots ?? defaultSlots;

  return (
    <div className="flex flex-wrap items-center gap-2">
      <Checkbox
        id={`weekday-${weekday}-date-${date}`}
        checked={!excluded}
        onCheckedChange={onToggle}
        data-testid={`checkbox-weekday-${weekday}-date-${date}`}
      />
      <Label
        htmlFor={`weekday-${weekday}-date-${date}`}
        className="text-sm font-normal cursor-pointer w-12 tabular-nums"
      >
        {formatDayMonth(date)}
      </Label>

      {excluded ? (
        <span className="text-xs text-muted-foreground">sem culto</span>
      ) : (
        <>
          {/* Nome do evento daquela data. Vazio herda o nome do dia — que é o
              placeholder, então dá para ver o que será usado sem preencher. */}
          <Input
            aria-label={`Nome do evento de ${formatDayMonth(date)}`}
            className="h-8 flex-1 min-w-[7rem]"
            value={title ?? ""}
            placeholder={defaultTitle}
            onChange={(e) => onTitleChange(e.target.value)}
            data-testid={`input-weekday-${weekday}-date-${date}-title`}
          />
          {shown.map((slot, index) => (
            <div key={slot.id} className="flex items-center gap-1">
              <Input
                type="time"
                aria-label={`Horário de ${formatDayMonth(date)}`}
                className="w-28 h-8"
                value={slot.time}
                onChange={(e) => onTimeChange(slot.id, e.target.value)}
                data-testid={`input-weekday-${weekday}-date-${date}-slot-${index}-time`}
              />
              {shown.length > 1 && (
                <Button
                  type="button"
                  variant="ghost"
                  size="icon"
                  className="h-8 w-8"
                  onClick={() => onRemoveSlot(slot.id)}
                  title="Remover este horário desta data"
                  data-testid={`button-weekday-${weekday}-date-${date}-remove-slot-${index}`}
                >
                  <Trash2 className="w-4 h-4 text-muted-foreground" />
                </Button>
              )}
            </div>
          ))}
          <Button
            type="button"
            variant="ghost"
            size="icon"
            className="h-8 w-8"
            onClick={onAddSlot}
            title="Adicionar horário nesta data"
            data-testid={`button-weekday-${weekday}-date-${date}-add-slot`}
          >
            <Plus className="w-4 h-4 text-muted-foreground" />
          </Button>
          {custom && (
            <>
              <Badge variant="secondary" className="text-xs font-normal whitespace-nowrap">
                horário próprio
              </Badge>
              <Button
                type="button"
                variant="ghost"
                size="icon"
                className="h-8 w-8"
                onClick={onReset}
                title="Usar o horário padrão do dia"
                data-testid={`button-weekday-${weekday}-date-${date}-reset`}
              >
                <RotateCcw className="w-4 h-4 text-muted-foreground" />
              </Button>
            </>
          )}
        </>
      )}
    </div>
  );
}

// "2026-08-08" → "08/08". O dia da semana já é o card que contém a data.
function formatDayMonth(date: string): string {
  try {
    return format(parseISO(date), "dd/MM");
  } catch {
    return date;
  }
}
