import { useMemo, useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { parseISO } from "date-fns";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle,
} from "@/components/ui/dialog";
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue,
} from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";
import { AlertTriangle, Sparkles } from "lucide-react";
import {
  SCHEDULE_ROLES, SCHEDULE_ROLE_LABELS,
  type SafeUser, type Schedule, type ScheduleRole, type Unavailability,
} from "@shared/schema";
import {
  autoGenerateSchedules, datesForWeekdays, formatScheduleDate, todayISO,
  type RolesByWeekday,
} from "@/lib/escalas";

const WEEKDAY_OPTIONS = [
  { value: 0, label: "Domingo" },
  { value: 4, label: "Quinta" },
  { value: 6, label: "Sábado" },
];

interface AutoGenerateDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  volunteers: SafeUser[]; // registered users; only those with roles are scheduled
  schedules: Schedule[];
  unavailability: Unavailability[];
}

export function AutoGenerateDialog({ open, onOpenChange, volunteers, schedules, unavailability }: AutoGenerateDialogProps) {
  const { toast } = useToast();
  const [startDate, setStartDate] = useState(todayISO());
  const [weeks, setWeeks] = useState("4");
  // Each selected weekday carries the functions to be filled on that day
  const [rolesByWeekday, setRolesByWeekday] = useState<RolesByWeekday>({ 0: [...SCHEDULE_ROLES] });
  const [time, setTime] = useState("18:00");
  const [title, setTitle] = useState("Culto");

  const result = useMemo(() => {
    if (!startDate) return { generated: [], skippedDates: [] };
    const dates = datesForWeekdays(parseISO(startDate), Number(weeks), rolesByWeekday);
    if (dates.length === 0) return { generated: [], skippedDates: [] };
    return autoGenerateSchedules({
      volunteers,
      existing: schedules,
      unavailability,
      dates,
      time,
      title: title.trim() || "Culto",
    });
  }, [startDate, weeks, rolesByWeekday, time, title, volunteers, schedules, unavailability]);

  const mutation = useMutation({
    mutationFn: async () => {
      const res = await apiRequest("POST", "/api/schedules/bulk", { schedules: result.generated });
      return res.json();
    },
    onSuccess: (created: Schedule[]) => {
      queryClient.invalidateQueries({ queryKey: ["/api/schedules"] });
      toast({ title: "Escalas geradas", description: `${created.length} escala(s) criada(s) automaticamente.` });
      onOpenChange(false);
    },
    onError: () => {
      toast({ title: "Erro", description: "Não foi possível gerar as escalas.", variant: "destructive" });
    },
  });

  // Toggling a weekday on selects all functions by default
  const toggleWeekday = (weekday: number) => {
    setRolesByWeekday((prev) => {
      const next = { ...prev };
      if (next[weekday]) {
        delete next[weekday];
      } else {
        next[weekday] = [...SCHEDULE_ROLES];
      }
      return next;
    });
  };

  const toggleRole = (weekday: number, role: ScheduleRole) => {
    setRolesByWeekday((prev) => {
      const current = prev[weekday] ?? [];
      return {
        ...prev,
        [weekday]: current.includes(role)
          ? current.filter((r) => r !== role)
          : [...current, role],
      };
    });
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Sparkles className="w-4 h-4 text-primary" /> Gerar escalas automaticamente
          </DialogTitle>
          <DialogDescription>
            Os voluntários são distribuídos por rodízio, priorizando quem tem menos escalas e respeitando as indisponibilidades registradas.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4">
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
            <div className="space-y-2">
              <Label htmlFor="gen-start">A partir de</Label>
              <Input
                id="gen-start"
                type="date"
                value={startDate}
                onChange={(e) => setStartDate(e.target.value)}
                data-testid="input-gen-start"
              />
            </div>
            <div className="space-y-2">
              <Label>Período</Label>
              <Select value={weeks} onValueChange={setWeeks}>
                <SelectTrigger data-testid="select-gen-weeks">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {[1, 2, 4, 6, 8].map((w) => (
                    <SelectItem key={w} value={String(w)}>{w} semana{w > 1 ? "s" : ""}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="gen-time">Horário</Label>
              <Input
                id="gen-time"
                type="time"
                value={time}
                onChange={(e) => setTime(e.target.value)}
                data-testid="input-gen-time"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="gen-title">Título</Label>
              <Input
                id="gen-title"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                data-testid="input-gen-title"
              />
            </div>
          </div>

          <div className="space-y-2">
            <Label>Dias da semana e funções</Label>
            <div className="space-y-2">
              {WEEKDAY_OPTIONS.map(({ value, label }) => {
                const selectedRoles = rolesByWeekday[value];
                const enabled = Boolean(selectedRoles);
                return (
                  <div key={value} className="border border-border rounded-lg p-3 space-y-2">
                    <div className="flex items-center gap-2">
                      <Checkbox
                        id={`weekday-${value}`}
                        checked={enabled}
                        onCheckedChange={() => toggleWeekday(value)}
                        data-testid={`checkbox-weekday-${value}`}
                      />
                      <Label htmlFor={`weekday-${value}`} className="font-medium cursor-pointer">{label}</Label>
                    </div>
                    {enabled && (
                      <div className="flex flex-wrap gap-x-4 gap-y-2 pl-6">
                        {SCHEDULE_ROLES.map((role) => (
                          <div key={role} className="flex items-center gap-2">
                            <Checkbox
                              id={`weekday-${value}-role-${role}`}
                              checked={selectedRoles!.includes(role)}
                              onCheckedChange={() => toggleRole(value, role)}
                              data-testid={`checkbox-weekday-${value}-role-${role}`}
                            />
                            <Label
                              htmlFor={`weekday-${value}-role-${role}`}
                              className="font-normal text-sm cursor-pointer"
                            >
                              {SCHEDULE_ROLE_LABELS[role]}
                            </Label>
                          </div>
                        ))}
                        {selectedRoles!.length === 0 && (
                          <span className="text-xs text-muted-foreground">
                            Selecione ao menos uma função para gerar escalas neste dia.
                          </span>
                        )}
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>

          {result.skippedDates.length > 0 && (
            <div className="flex items-start gap-2 bg-muted/50 border border-border rounded-lg p-3">
              <AlertTriangle className="w-4 h-4 text-muted-foreground mt-0.5 shrink-0" />
              <p className="text-xs text-muted-foreground">
                Datas ignoradas por já possuírem escala: {result.skippedDates.join(", ")}
              </p>
            </div>
          )}

          {/* Preview */}
          <div className="space-y-2">
            <Label>Pré-visualização ({result.generated.length} escala{result.generated.length !== 1 ? "s" : ""})</Label>
            {result.generated.length === 0 ? (
              <p className="text-sm text-muted-foreground border border-border rounded-lg p-4 text-center">
                Nenhuma data disponível com os critérios selecionados.
              </p>
            ) : (
              <div className="space-y-2 max-h-[240px] overflow-y-auto pr-1">
                {result.generated.map((s) => (
                  <div key={s.eventDate} className="border border-border rounded-lg p-3 space-y-1.5">
                    <p className="text-sm font-semibold">
                      {formatScheduleDate(s.eventDate)} · {s.eventTime}
                    </p>
                    <div className="flex flex-wrap gap-1.5">
                      {s.assignments.map((a) => (
                        <Badge key={a.role} variant="secondary" className="text-xs font-normal">
                          <span className="font-semibold mr-1">{SCHEDULE_ROLE_LABELS[a.role]}:</span> {a.volunteerName}
                        </Badge>
                      ))}
                      {s.assignments.length === 0 && (
                        <span className="text-xs text-muted-foreground">Sem voluntários elegíveis</span>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>

        <DialogFooter>
          <Button variant="secondary" onClick={() => onOpenChange(false)}>Cancelar</Button>
          <Button
            onClick={() => mutation.mutate()}
            disabled={mutation.isPending || result.generated.length === 0}
            data-testid="button-generate-schedules"
          >
            {mutation.isPending ? "Gerando..." : `Salvar ${result.generated.length} escala(s)`}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
