import { useMemo, useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { parseISO } from "date-fns";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle,
} from "@/components/ui/dialog";
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue,
} from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";
import { AlertTriangle, ChevronDown, ChevronUp, Plus, Sparkles, Trash2 } from "lucide-react";
import {
  SCHEDULE_ROLES, SCHEDULE_ROLE_LABELS,
  type SafeUser, type Schedule, type ScheduleRole, type Unavailability,
} from "@shared/schema";
import {
  autoGenerateSchedules, datesForWeekdays, defaultSlotsForWeekday, formatScheduleDate,
  makeScheduleSlot, todayISO,
  type AutoGenerateResult, type ScheduleSlot, type SlotsByWeekday,
} from "@/lib/escalas";

// Os dias em que a igreja tem culto regularmente
const MAIN_WEEKDAY_OPTIONS = [
  { value: 0, label: "Domingo" },
  { value: 4, label: "Quinta" },
  { value: 6, label: "Sábado" },
];

// Ficam escondidos atrás de "Outros dias": raramente usados, mas existem para
// eventos ocasionais fora dos dias de culto.
const OTHER_WEEKDAY_OPTIONS = [
  { value: 1, label: "Segunda" },
  { value: 2, label: "Terça" },
  { value: 3, label: "Quarta" },
  { value: 5, label: "Sexta" },
];

interface AutoGenerateDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  volunteers: SafeUser[]; // registered users; only those with roles are scheduled
  schedules: Schedule[];
  unavailability: Unavailability[];
}

export function AutoGenerateDialog({ open, onOpenChange, volunteers, schedules, unavailability }: AutoGenerateDialogProps) {
  const { toast } = useToast();
  const [startDate, setStartDate] = useState(todayISO());
  const [weeks, setWeeks] = useState("4");
  // Cada dia selecionado guarda seus cultos (horário + funções a preencher).
  // Domingo já começa com dois: culto da manhã e culto da noite.
  const [slotsByWeekday, setSlotsByWeekday] = useState<SlotsByWeekday>({ 0: defaultSlotsForWeekday(0) });
  const [title, setTitle] = useState("Culto");
  const [showOtherDays, setShowOtherDays] = useState(false);

  const otherDaysSelected = OTHER_WEEKDAY_OPTIONS.filter(({ value }) => slotsByWeekday[value]).length;

  const result = useMemo(() => {
    const empty: AutoGenerateResult = { generated: [], skipped: [] };
    if (!startDate) return empty;
    const dates = datesForWeekdays(parseISO(startDate), Number(weeks), slotsByWeekday);
    if (dates.length === 0) return empty;
    return autoGenerateSchedules({
      volunteers,
      existing: schedules,
      unavailability,
      dates,
      title: title.trim() || "Culto",
    });
  }, [startDate, weeks, slotsByWeekday, title, volunteers, schedules, unavailability]);

  const mutation = useMutation({
    mutationFn: async () => {
      const res = await apiRequest("POST", "/api/schedules/bulk", { schedules: result.generated });
      return res.json();
    },
    onSuccess: (created: Schedule[]) => {
      queryClient.invalidateQueries({ queryKey: ["/api/schedules"] });
      toast({ title: "Escalas geradas", description: `${created.length} escala(s) criada(s) automaticamente.` });
      onOpenChange(false);
    },
    onError: () => {
      toast({ title: "Erro", description: "Não foi possível gerar as escalas.", variant: "destructive" });
    },
  });

  // Marcar um dia já traz os horários padrão dele, com todas as funções
  const toggleWeekday = (weekday: number) => {
    setSlotsByWeekday((prev) => {
      const next = { ...prev };
      if (next[weekday]) {
        delete next[weekday];
      } else {
        next[weekday] = defaultSlotsForWeekday(weekday);
      }
      return next;
    });
  };

  const updateSlots = (weekday: number, update: (slots: ScheduleSlot[]) => ScheduleSlot[]) => {
    setSlotsByWeekday((prev) => ({ ...prev, [weekday]: update(prev[weekday] ?? []) }));
  };

  const addSlot = (weekday: number) =>
    updateSlots(weekday, (slots) => [...slots, makeScheduleSlot()]);

  const removeSlot = (weekday: number, slotId: string) =>
    updateSlots(weekday, (slots) => slots.filter((s) => s.id !== slotId));

  const setSlotTime = (weekday: number, slotId: string, time: string) =>
    updateSlots(weekday, (slots) => slots.map((s) => (s.id === slotId ? { ...s, time } : s)));

  const toggleSlotRole = (weekday: number, slotId: string, role: ScheduleRole) =>
    updateSlots(weekday, (slots) =>
      slots.map((s) =>
        s.id === slotId
          ? {
              ...s,
              roles: s.roles.includes(role) ? s.roles.filter((r) => r !== role) : [...s.roles, role],
            }
          : s
      )
    );

  const weekdayCard = ({ value, label }: { value: number; label: string }) => (
    <WeekdayCard
      key={value}
      weekday={value}
      label={label}
      slots={slotsByWeekday[value]}
      onToggle={() => toggleWeekday(value)}
      onAddSlot={() => addSlot(value)}
      onRemoveSlot={(slotId) => removeSlot(value, slotId)}
      onTimeChange={(slotId, time) => setSlotTime(value, slotId, time)}
      onToggleRole={(slotId, role) => toggleSlotRole(value, slotId, role)}
    />
  );

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Sparkles className="w-4 h-4 text-primary" /> Gerar escalas automaticamente
          </DialogTitle>
          <DialogDescription>
            Os voluntários são distribuídos por rodízio, priorizando quem tem menos escalas e respeitando as indisponibilidades registradas — inclusive o período (manhã, tarde ou noite) de cada culto.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4">
          <div className="grid grid-cols-2 sm:grid-cols-3 gap-4">
            <div className="space-y-2">
              <Label htmlFor="gen-start">A partir de</Label>
              <Input
                id="gen-start"
                type="date"
                value={startDate}
                onChange={(e) => setStartDate(e.target.value)}
                data-testid="input-gen-start"
              />
            </div>
            <div className="space-y-2">
              <Label>Período</Label>
              <Select value={weeks} onValueChange={setWeeks}>
                <SelectTrigger data-testid="select-gen-weeks">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {[1, 2, 4, 6, 8].map((w) => (
                    <SelectItem key={w} value={String(w)}>{w} semana{w > 1 ? "s" : ""}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="gen-title">Título</Label>
              <Input
                id="gen-title"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                data-testid="input-gen-title"
              />
            </div>
          </div>

          <div className="space-y-2">
            <div>
              <Label>Dias, horários e funções</Label>
              <p className="text-xs text-muted-foreground mt-1">
                Cada horário vira uma escala. Domingo já vem com os dois cultos (manhã e noite) —
                use “Adicionar horário” para incluir outros cultos no mesmo dia.
              </p>
            </div>
            <div className="space-y-2">
              {MAIN_WEEKDAY_OPTIONS.map(weekdayCard)}
            </div>

            {/* Dias fora dos cultos regulares: escondidos, mas disponíveis para
                eventos ocasionais */}
            <div className="space-y-2">
              <Button
                type="button"
                variant="ghost"
                size="sm"
                className="w-full justify-center text-muted-foreground"
                onClick={() => setShowOtherDays((v) => !v)}
                data-testid="button-other-weekdays"
              >
                {showOtherDays ? <ChevronUp className="w-4 h-4 mr-1" /> : <ChevronDown className="w-4 h-4 mr-1" />}
                Outros dias
                {!showOtherDays && otherDaysSelected > 0 && (
                  <Badge variant="secondary" className="ml-2 text-xs font-normal">
                    {otherDaysSelected} selecionado{otherDaysSelected > 1 ? "s" : ""}
                  </Badge>
                )}
              </Button>
              {showOtherDays && (
                <div className="space-y-2">
                  {OTHER_WEEKDAY_OPTIONS.map(weekdayCard)}
                </div>
              )}
            </div>
          </div>

          {result.skipped.length > 0 && (
            <div className="flex items-start gap-2 bg-muted/50 border border-border rounded-lg p-3">
              <AlertTriangle className="w-4 h-4 text-muted-foreground mt-0.5 shrink-0" />
              <p className="text-xs text-muted-foreground">
                Ignorados por já possuírem escala:{" "}
                {result.skipped.map(({ date, time }) => `${date} ${time}`).join(", ")}
              </p>
            </div>
          )}

          {/* Preview */}
          <div className="space-y-2">
            <Label>Pré-visualização ({result.generated.length} escala{result.generated.length !== 1 ? "s" : ""})</Label>
            {result.generated.length === 0 ? (
              <p className="text-sm text-muted-foreground border border-border rounded-lg p-4 text-center">
                Nenhuma data disponível com os critérios selecionados.
              </p>
            ) : (
              <div className="space-y-2 max-h-[240px] overflow-y-auto pr-1">
                {result.generated.map((s) => (
                  <div key={`${s.eventDate} ${s.eventTime}`} className="border border-border rounded-lg p-3 space-y-1.5">
                    <p className="text-sm font-semibold">
                      {formatScheduleDate(s.eventDate)} · {s.eventTime}
                    </p>
                    <div className="flex flex-wrap gap-1.5">
                      {s.assignments.map((a) => (
                        <Badge key={a.role} variant="secondary" className="text-xs font-normal">
                          <span className="font-semibold mr-1">{SCHEDULE_ROLE_LABELS[a.role]}:</span> {a.volunteerName}
                        </Badge>
                      ))}
                      {s.assignments.length === 0 && (
                        <span className="text-xs text-muted-foreground">Sem voluntários elegíveis</span>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>

        <DialogFooter>
          <Button variant="secondary" onClick={() => onOpenChange(false)}>Cancelar</Button>
          <Button
            onClick={() => mutation.mutate()}
            disabled={mutation.isPending || result.generated.length === 0}
            data-testid="button-generate-schedules"
          >
            {mutation.isPending ? "Gerando..." : `Salvar ${result.generated.length} escala(s)`}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// Um dia da semana: quando marcado, lista seus cultos (horário + funções)
function WeekdayCard({ weekday, label, slots, onToggle, onAddSlot, onRemoveSlot, onTimeChange, onToggleRole }: {
  weekday: number;
  label: string;
  slots?: ScheduleSlot[];
  onToggle: () => void;
  onAddSlot: () => void;
  onRemoveSlot: (slotId: string) => void;
  onTimeChange: (slotId: string, time: string) => void;
  onToggleRole: (slotId: string, role: ScheduleRole) => void;
}) {
  const enabled = Boolean(slots);

  return (
    <div className="border border-border rounded-lg p-3 space-y-2">
      <div className="flex items-center gap-2">
        <Checkbox
          id={`weekday-${weekday}`}
          checked={enabled}
          onCheckedChange={onToggle}
          data-testid={`checkbox-weekday-${weekday}`}
        />
        <Label htmlFor={`weekday-${weekday}`} className="font-medium cursor-pointer">{label}</Label>
        {enabled && slots!.length > 1 && (
          <span className="text-xs text-muted-foreground ml-auto">{slots!.length} horários</span>
        )}
      </div>

      {enabled && (
        <div className="space-y-2 pl-6">
          {slots!.map((slot, index) => (
            <div key={slot.id} className="border border-border/70 bg-muted/30 rounded-md p-2.5 space-y-2">
              <div className="flex items-center gap-2">
                <Label htmlFor={`weekday-${weekday}-slot-${index}-time`} className="text-xs text-muted-foreground">
                  {slots!.length > 1 ? `Horário ${index + 1}` : "Horário"}
                </Label>
                <Input
                  id={`weekday-${weekday}-slot-${index}-time`}
                  type="time"
                  className="w-32 h-8"
                  value={slot.time}
                  onChange={(e) => onTimeChange(slot.id, e.target.value)}
                  data-testid={`input-weekday-${weekday}-slot-${index}-time`}
                />
                {slots!.length > 1 && (
                  <Button
                    type="button"
                    variant="ghost"
                    size="icon"
                    className="h-8 w-8 ml-auto"
                    onClick={() => onRemoveSlot(slot.id)}
                    title="Remover horário"
                    data-testid={`button-weekday-${weekday}-remove-slot-${index}`}
                  >
                    <Trash2 className="w-4 h-4 text-muted-foreground" />
                  </Button>
                )}
              </div>

              <div className="flex flex-wrap gap-x-4 gap-y-2">
                {SCHEDULE_ROLES.map((role) => (
                  <div key={role} className="flex items-center gap-2">
                    <Checkbox
                      id={`weekday-${weekday}-slot-${index}-role-${role}`}
                      checked={slot.roles.includes(role)}
                      onCheckedChange={() => onToggleRole(slot.id, role)}
                      data-testid={`checkbox-weekday-${weekday}-slot-${index}-role-${role}`}
                    />
                    <Label
                      htmlFor={`weekday-${weekday}-slot-${index}-role-${role}`}
                      className="font-normal text-sm cursor-pointer"
                    >
                      {SCHEDULE_ROLE_LABELS[role]}
                    </Label>
                  </div>
                ))}
                {slot.roles.length === 0 && (
                  <span className="text-xs text-muted-foreground">
                    Selecione ao menos uma função para gerar escala neste horário.
                  </span>
                )}
              </div>
            </div>
          ))}

          <Button
            type="button"
            variant="ghost"
            size="sm"
            className="text-muted-foreground"
            onClick={onAddSlot}
            data-testid={`button-weekday-${weekday}-add-slot`}
          >
            <Plus className="w-4 h-4 mr-1" /> Adicionar horário
          </Button>
        </div>
      )}
    </div>
  );
}
